stages:
    - test
    - build
    - e2e-test
    - deploy

variables:
    RULES_CHANGES_PATH: "**/*"
    BACKEND_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME-backend:latest
    FRONTEND_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME-frontend:latest
    CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"
    POSTGRES_HOST: postgres
    POSTGRES_PORT: 5432
    POSTGRES_USER: todo
    POSTGRES_PASSWORD: todo
    POSTGRES_DB: todo
    POSTGRES_HOST_AUTH_METHOD: trust

.base-rules:
    rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
          when: always
        - if: '$CI_PIPELINE_SOURCE == "push"'
          when: never
        - if: $CI_COMMIT_TAG
          when: never
        - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
          changes:
              - $RULES_CHANGES_PATH
        - when: manual
          allow_failure: true

.backend:
    extends: .base-rules
    variables:
        RULES_CHANGES_PATH: "backend/**/*"

.frontend:
    extends: .base-rules
    variables:
        RULES_CHANGES_PATH: "frontend/**/*"

backend-test:
    image: golang:1.17-buster
    extends: .backend
    stage: test
    variables:
        GOPATH: $CI_PROJECT_DIR/.go
        DB_HOST: $POSTGRES_HOST
        DB_PORT: $POSTGRES_PORT
        DB_USER: $POSTGRES_USER
        DB_PASSWORD: $POSTGRES_PASSWORD
        DB_DATABASE: $POSTGRES_DB
    cache:
        paths:
            - .go/pkg/mod/

    services:
        - name: postgres:12-alpine
          alias: ${POSTGRES_HOST}

    before_script:
        - apt update
        - apt install -y postgresql-client
        - export PGPASSWORD=$POSTGRES_PASSWORD
        - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -f ./backend/db.sql
        - mkdir -p .go
    script:
        - cd backend
        - go mod download
        - go mod verify
        - go test -v ./...

frontend-test:
    image: node:14-alpine
    extends: .frontend
    stage: test
    cache:
        key:
            files:
                - yarn.lock
        paths:
            - .yarn-cache/
    script:
        - cd frontend
        - yarn install --cache-folder .yarn-cache
        - yarn test:unit

backend-build:
    image: docker:latest
    extends: .backend
    stage: build
    needs: ["backend-test"]
    services:
        - docker:dind
    before_script:
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
        - docker pull $BACKEND_LATEST
    script:
        - docker build --cache-from $BACKEND_LATEST --tag $BACKEND_LATEST --target prod ./backend
        - docker push $BACKEND_LATEST

frontend-build:
    image: docker:latest
    extends: .frontend
    stage: build
    needs: ["frontend-test"]
    services:
        - docker:dind
    before_script:
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
        - docker pull $FRONTEND_LATEST
    script:
        - docker build --cache-from $FRONTEND_LATEST --tag $FRONTEND_LATEST --target prod ./frontend
        - docker push $FRONTEND_LATEST

e2e-test:
    image: cypress/browsers:node14.17.0-chrome88-ff89
    cache:
        key: ${CI_COMMIT_REF_SLUG}
        paths:
            - cache/Cypress
            - node_modules

    services:
        - name: postgres:12-alpine
          alias: ${POSTGRES_HOST}

        - name: ${BACKEND_LATEST}
          alias: backend

        - name: ${FRONTEND_LATEST}
          alias: frontend

    variables:
        FF_NETWORK_PER_BUILD: 1
        LISTEN_ADDR: "127.0.0.1:8080"
        BACKEND_URL: http://backend
        NGINX_PORT: 5050
        CYPRESS_BASE_URL: http://frontend:5050
        CYPRESS_PGDATABASE: $POSTGRES_DB
        CYPRESS_PGHOST: $POSTGRES_HOST
        CYPRESS_PGPORT: $POSTGRES_PORT
        CYPRESS_PGUSER: $POSTGRES_USER
        CYPRESS_PGPASSWORD: $POSTGRES_PASSWORD
        DB_HOST: $POSTGRES_HOST
        DB_PORT: $POSTGRES_PORT
        DB_USER: $POSTGRES_USER
        DB_PASSWORD: $POSTGRES_PASSWORD
        DB_DATABASE: $POSTGRES_DB

    stage: e2e-test
    needs: ["backend-build", "frontend-build"]

    before_script:
        - apt update
        - apt install -y postgresql-client
        - export PGPASSWORD=$POSTGRES_PASSWORD
        - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -f ./backend/db.sql

    script:
        - yarn install --frozen-lockfile
        - npx cypress cache path
        - npx cypress cache list
        - yarn cy:run

deploy:
    image: alpine:latest
    stage: deploy

    script:
        - echo "Deploying"
