version: "3.4"

services:
  backend:
    image: monorepo/backend:latest
    build:
      context: backend
      target: prod
    environment:
      - LISTEN_ADDR=127.0.0.1:8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=todo
      - DB_PASSWORD=todo
      - DB_DATABASE=todo

  frontend:
    image: monorepo/frontend:latest
    build:
      context: frontend
      target: prod
    ports:
      - "5050:5050"

    environment:
      - BACKEND_URL=http://backend
      - NGINX_PORT=5050

  postgres:
    image: postgres:12-alpine
    ports:
      - "127.0.0.1:5422:5432"

    volumes:
      - ./backend/db.sql:/docker-entrypoint-initdb.d/db.sql

    environment:
      - POSTGRES_USER=todo
      - POSTGRES_PASSWORD=todo
      - POSTGRES_DB=todo
      - POSTGRES_HOST_AUTH_METHOD=trust
